version: "3.3"

services:
  postgres:
    build: ./database
    image: appsec-postgres:02-01
    env_file: ./server/.env
    networks:
      - backend
    ports:
      - "5432:5432"
  apiserver:
    image: "node:8"
    env_file: ./server/.env
    working_dir: /home/node/server
    depends_on: 
      - postgres
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./server:/home/node/server
    entrypoint: "/home/node/server/scripts/entrypoint.sh"
  frontend:
    image: "httpd:2.4"
    volumes:
      - ./front-end:/usr/local/apache2/htdocs/
    networks:
      - backend
    ports:
      - "8080:80"

networks:
  backend: